language: cpp

compiler:
    - gcc

before_install:
    - sudo apt-get install --yes --force-yes python3-pip 
    - pip3 install meson
    - wget https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-linux.zip
    - unzip ninja-linux.zip -d ${HOME}/.local/bin

before_script:
    - mkdir build
    - cd build
    - meson build

script:
    - mesontest -C build 
    - DESTDIR=$(mktemp -d) ninja -C build -v install
