language: cpp

compiler:
    - gcc

before_install:
    - sudo apt-get update
    - sudo apt-get -qq install gcc-5 g++-5 libstdc++-5-dev libcppunit-dev python3.4 python3-pip unzip
    - pip3 install meson

install:
    - wget https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-linux.zip
    - unzip ninja-linux.zip -d ${HOME}/.local/bin

before_script:
    - mkdir build
    - cd build
    - meson build

script:
    - mesontest -C build 
    - DESTDIR=$(mktemp -d) ninja -C build -v install
